; global data symbols, MUST directly follow function_pointers

; class GameWorld ou; // RVA = 0x2131020 Global
?ou@@3PEAVGameWorld@@EA proc EXPORT
QWORD 0
?ou@@3PEAVGameWorld@@EA endp

; class GlobalConstants con; // RVA = 0x2130CE0 Global
?con@@3PEAVGlobalConstants@@EA proc EXPORT
QWORD 0
?con@@3PEAVGlobalConstants@@EA endp

; class InputHandler key; // RVA = 0x2130290 Global
?key@@3PEAVInputHandler@@EA proc EXPORT
QWORD 0
?key@@3PEAVInputHandler@@EA endp

; class OptionsHolder options; // RVA = 0x21303B0 Global
?options@@3PEAVOptionsHolder@@EA proc EXPORT
QWORD 0
?options@@3PEAVOptionsHolder@@EA endp

; class ForgottenGUI gui; // RVA = 0x21306C0 Global
?gui@@3PEAVForgottenGUI@@EA proc EXPORT
QWORD 0
?gui@@3PEAVForgottenGUI@@EA endp

; class KingOfRenderThread au; // RVA = 0x2130220 Global
?au@@3PEAVKingOfRenderThread@@EA proc EXPORT
QWORD 0
?au@@3PEAVKingOfRenderThread@@EA endp

; class std::locale globalLocale; // RVA = 0x212FE28 Global
?globalLocale@@3PEAVlocale@std@@EA proc EXPORT
QWORD 0
?globalLocale@@3PEAVlocale@std@@EA endp

; class SharedKing shou; // RVA = 0x2131008 Global
?shou@@3PEAVSharedKing@@EA proc EXPORT
QWORD 0
?shou@@3PEAVSharedKing@@EA endp
